"use client";

import { Eye, FileCheck2, Printer, RefreshCw, Search, Settings2 } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { toast } from "sonner";

import { useRealtimeRefresh } from "@/components/realtime-provider";
import { InvoiceDocumentPages, type InvoicePrintDocument } from "@/components/invoices/invoice-document";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { InvoiceTemplateConfig, InvoiceTemplateView } from "@/lib/invoice-templates/config";

type SiteOption = { id: string; name: string };
type Candidate = { id: string; siteId: string; siteCode: string; siteName: string; siteAddress: string | null; revenueDate: string; title: string; description: string | null; itemName: string | null; quantity: number | null; unit: string | null; unitPrice: number | null; supplyAmount: number; sourceType: "CONTRACT" | "MANUAL" | "ADJUSTMENT" };
type CandidateData = { rows: Candidate[]; total: number; truncated: boolean; totals: { supplyAmount: number; taxAmount: number } };
type InvoiceRow = { id: string; invoiceNo: string; issueDate: string; periodStart: string; periodEnd: string; recipientName: string; subtotal: number; taxAmount: number; totalAmount: number; displayMode: "AGGREGATED" | "ITEMIZED"; issuedAt: string; _count: { lines: number; revenueLinks: number } };
export type InvoiceList = { rows: InvoiceRow[]; total: number; page: number; pageSize: number; totalPages: number };
type PreviewDocument = { siteId: string; siteName: string; siteAddress: string | null; issueDate: string; memo: string | null; templateConfig: InvoiceTemplateConfig; supplier: { businessRegistrationNo: string; companyName: string; representativeName: string; address: string; businessType: string; businessItem: string; phone: string; defaultMessage: string }; lines: Array<{ itemName: string; specification: string | null; quantity: number | null; unit: string | null; unitPrice: number | null; supplyAmount: number; taxAmount: number; revenueEntryIds: string[] }>; subtotal: number; taxAmount: number; totalAmount: number };
type IssuePayload = { revenueEntryIds: string[]; periodStart: string; periodEnd: string; issueDate: string; displayMode: "AGGREGATED" | "ITEMIZED"; memo: string | null; templateId: string; templateVersion: number };

export function InvoiceManager({ initialData, sites, templates, canIssue, companyComplete, isAdmin }: { initialData: InvoiceList; sites: SiteOption[]; templates: InvoiceTemplateView[]; canIssue: boolean; companyComplete: boolean; isAdmin: boolean }) {
  const now = new Date(); const today = localDateKey(now); const monthStart = `${today.slice(0, 7)}-01`; const monthEnd = localDateKey(new Date(now.getFullYear(), now.getMonth() + 1, 0));
  const [data, setData] = useState(initialData); const [candidates, setCandidates] = useState<CandidateData | null>(null); const [selected, setSelected] = useState<string[]>([]); const [startDate, setStartDate] = useState(monthStart); const [endDate, setEndDate] = useState(monthEnd); const [siteId, setSiteId] = useState(""); const [issueDate, setIssueDate] = useState(today); const [displayMode, setDisplayMode] = useState<"AGGREGATED" | "ITEMIZED">("AGGREGATED"); const [memo, setMemo] = useState(""); const [templateId, setTemplateId] = useState(templates[0]?.id ?? "system-default"); const [preview, setPreview] = useState<PreviewDocument[] | null>(null); const [pending, setPending] = useState<IssuePayload | null>(null); const [busy, setBusy] = useState(false);
  async function loadCandidates() { setBusy(true); try { const params = new URLSearchParams({ startDate, endDate, siteId }); const response = await fetch(`/api/invoices/candidates?${params}`); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "발행 후보를 불러오지 못했습니다."); setCandidates(body); setSelected([]); setPreview(null); setPending(null); } catch (error) { toast.error(error instanceof Error ? error.message : "발행 후보를 불러오지 못했습니다."); } finally { setBusy(false); } }
  async function loadInvoices(page = data.page) { const response = await fetch(`/api/invoices?page=${page}&pageSize=20`); const body = await response.json(); if (response.ok) setData(body); }
  useRealtimeRefresh(["invoice.changed"], () => { void loadInvoices(); if (candidates) void loadCandidates(); });
  function toggle(id: string) { setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]); setPreview(null); setPending(null); }
  function selectAll() { if (!candidates) return; setSelected(selected.length === candidates.rows.length ? [] : candidates.rows.map((row) => row.id)); setPreview(null); setPending(null); }
  async function showPreview() { if (!selected.length) return toast.error("발행할 매출을 선택해 주세요."); const template = templates.find((item) => item.id === templateId) ?? templates[0]; if (!template) return toast.error("사용할 템플릿을 선택해 주세요."); const payload: IssuePayload = { revenueEntryIds: selected, periodStart: startDate, periodEnd: endDate, issueDate, displayMode, memo: memo.trim() || null, templateId: template.id, templateVersion: template.version }; setBusy(true); try { const response = await fetch("/api/invoices/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "미리보기를 만들지 못했습니다."); setPreview(body.documents); setPending(payload); } catch (error) { toast.error(error instanceof Error ? error.message : "미리보기를 만들지 못했습니다."); } finally { setBusy(false); } }
  async function issue() { if (!pending) return; setBusy(true); try { const response = await fetch("/api/invoices", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(pending) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "거래명세표를 발행하지 못했습니다."); const ids = body.documents.map((document: { id: string }) => document.id); toast.success(`거래명세표 ${ids.length}건을 발행했습니다.`); setPreview(null); setPending(null); await Promise.all([loadCandidates(), loadInvoices(1)]); window.open(`/invoices/print?ids=${ids.join(",")}`, "_blank", "noopener,noreferrer"); } catch (error) { toast.error(error instanceof Error ? error.message : "거래명세표를 발행하지 못했습니다."); } finally { setBusy(false); } }
  const selectedRows = candidates?.rows.filter((row) => selected.includes(row.id)) ?? []; const selectedSupply = selectedRows.reduce((sum, row) => sum + row.supplyAmount, 0);
  return <div className="space-y-6">
    <div className="flex justify-end"><Button variant="outline" render={<Link href="/invoices/templates" />}><Settings2 data-icon="inline-start" />{canIssue ? "템플릿 관리" : "템플릿 보기"}</Button></div>
    {canIssue && <section id="new-issue" className="scroll-mt-20 space-y-4 rounded-xl border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">신규 발행</h2><p className="text-sm text-muted-foreground">확정되고 아직 발행되지 않은 매출만 표시합니다.</p></div>{!companyComplete && <div className="rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-sm text-amber-900">공급자 정보가 필요합니다. {isAdmin ? <Link className="underline" href="/settings/company">설정하기</Link> : "관리자에게 설정을 요청하세요."}</div>}</div>
      <div className="grid gap-3 md:grid-cols-4"><Field label="시작일" type="date" value={startDate} onChange={setStartDate} /><Field label="종료일" type="date" value={endDate} onChange={setEndDate} /><Select label="현장" value={siteId} onChange={setSiteId} options={[{ value: "", label: "전체 현장" }, ...sites.map((site) => ({ value: site.id, label: site.name }))]} /><div className="flex items-end"><Button className="w-full" variant="outline" disabled={busy} onClick={() => void loadCandidates()}><Search data-icon="inline-start" />후보 조회</Button></div></div>
      {candidates && <><div className="flex flex-wrap items-center justify-between gap-3"><div className="text-sm"><span className="font-medium">후보 {candidates.total}건</span>{candidates.truncated && <span className="ml-2 text-amber-700">최대 500건만 표시</span>}<span className="ml-3 text-muted-foreground">선택 {selected.length}건 · {selectedSupply.toLocaleString()}원</span></div><Button size="sm" variant="outline" onClick={selectAll}>{selected.length === candidates.rows.length ? "전체 해제" : "전체 선택"}</Button></div><div className="max-h-96 overflow-auto rounded-lg border"><Table><TableHeader><TableRow><TableHead className="w-10"></TableHead><TableHead>귀속일</TableHead><TableHead>현장</TableHead><TableHead>내용</TableHead><TableHead>수량·단가</TableHead><TableHead className="text-right">공급가액</TableHead></TableRow></TableHeader><TableBody>{candidates.rows.length === 0 ? <TableRow><TableCell colSpan={6} className="h-24 text-center text-muted-foreground">발행 가능한 매출이 없습니다.</TableCell></TableRow> : candidates.rows.map((row) => <TableRow key={row.id}><TableCell><input aria-label={`${row.title} 선택`} type="checkbox" checked={selected.includes(row.id)} onChange={() => toggle(row.id)} /></TableCell><TableCell>{row.revenueDate.slice(0, 10)}</TableCell><TableCell>{row.siteName}</TableCell><TableCell><span className="font-medium">{row.itemName ?? row.title}</span><span className="block text-xs text-muted-foreground">{row.description ?? row.title}</span></TableCell><TableCell className="text-xs">{row.quantity == null ? "직접 금액" : `${row.quantity} ${row.unit ?? ""} × ${(row.unitPrice ?? 0).toLocaleString()}`}</TableCell><TableCell className="text-right tabular-nums">{row.supplyAmount.toLocaleString()}</TableCell></TableRow>)}</TableBody></Table></div>
        <div className="grid gap-3 md:grid-cols-5"><Field label="발행일" type="date" value={issueDate} onChange={(value) => { setIssueDate(value); setPreview(null); }} /><Select label="표시 방식" value={displayMode} onChange={(value) => { setDisplayMode(value as "AGGREGATED" | "ITEMIZED"); setPreview(null); }} options={[{ value: "AGGREGATED", label: "동일 품목 합산" }, { value: "ITEMIZED", label: "원장 건별 표시" }]} /><Select label="출력 템플릿" value={templateId} onChange={(value) => { setTemplateId(value); setPreview(null); setPending(null); }} options={templates.map((template) => ({ value: template.id, label: template.name }))} /><Field label="메모" value={memo} onChange={(value) => { setMemo(value); setPreview(null); }} placeholder="선택" /><div className="flex items-end"><Button className="w-full" disabled={busy || !companyComplete || !selected.length} onClick={() => void showPreview()}><Eye data-icon="inline-start" />발행 미리보기</Button></div></div></>}
    </section>}
    <section className="space-y-3"><div className="flex items-center justify-between"><div><h2 className="font-semibold">발행 이력</h2><p className="text-sm text-muted-foreground">발행 당시 snapshot으로 언제든 재출력합니다.</p></div><Button size="sm" variant="outline" onClick={() => void loadInvoices()}><RefreshCw data-icon="inline-start" />새로고침</Button></div><div className="overflow-x-auto rounded-xl border bg-card"><Table><TableHeader><TableRow><TableHead>발행번호</TableHead><TableHead>발행일</TableHead><TableHead>수신처</TableHead><TableHead>귀속기간</TableHead><TableHead>원장/표시행</TableHead><TableHead className="text-right">공급가액</TableHead><TableHead>방식</TableHead><TableHead className="text-right">출력</TableHead></TableRow></TableHeader><TableBody>{data.rows.length === 0 ? <TableRow><TableCell colSpan={8} className="h-28 text-center text-muted-foreground">발행된 거래명세표가 없습니다.</TableCell></TableRow> : data.rows.map((row) => <TableRow key={row.id}><TableCell className="font-mono text-xs">{row.invoiceNo}</TableCell><TableCell>{row.issueDate.slice(0, 10)}</TableCell><TableCell>{row.recipientName}</TableCell><TableCell className="text-xs">{row.periodStart.slice(0, 10)} ~ {row.periodEnd.slice(0, 10)}</TableCell><TableCell>{row._count.revenueLinks}/{row._count.lines}</TableCell><TableCell className="text-right font-medium tabular-nums">{row.subtotal.toLocaleString()}</TableCell><TableCell><Badge variant="outline">{row.displayMode === "AGGREGATED" ? "합산" : "건별"}</Badge></TableCell><TableCell className="text-right"><Button size="sm" variant="ghost" render={<a href={`/invoices/print?ids=${row.id}`} target="_blank" rel="noreferrer" />}><Printer data-icon="inline-start" />재출력</Button></TableCell></TableRow>)}</TableBody></Table></div><div className="flex items-center justify-between text-sm text-muted-foreground"><span>총 {data.total}건 · {data.page}/{data.totalPages} 페이지</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={data.page <= 1} onClick={() => void loadInvoices(data.page - 1)}>이전</Button><Button size="sm" variant="outline" disabled={data.page >= data.totalPages} onClick={() => void loadInvoices(data.page + 1)}>다음</Button></div></div></section>
    {preview && <Dialog open onOpenChange={(open) => { if (!open) setPreview(null); }}><DialogContent className="max-h-[94svh] overflow-y-auto sm:max-w-6xl"><DialogHeader><DialogTitle>거래명세표 발행 미리보기</DialogTitle><DialogDescription>선택한 템플릿의 실제 A4 배치와 자동 페이지 나눔을 확인하세요. 발행 후에는 이 모습이 snapshot으로 유지됩니다.</DialogDescription></DialogHeader><div className="overflow-auto rounded-xl bg-slate-100 p-4"><InvoiceDocumentPages documents={preview.map(toPrintPreview)} /></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setPreview(null)}>돌아가기</Button><Button disabled={busy} onClick={() => void issue()}><FileCheck2 data-icon="inline-start" />{busy ? "발행 중..." : `${preview.length}건 발행`}</Button></div></DialogContent></Dialog>}
  </div>;
}

function Field({ label, value, onChange, type = "text", placeholder }: { label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string }) { return <div className="space-y-1.5"><Label>{label}</Label><Input type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></div>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: Array<{ value: string; label: string }> }) { return <div className="space-y-1.5"><Label>{label}</Label><select value={value} onChange={(event) => onChange(event.target.value)} className="h-9 w-full rounded-lg border bg-background px-3 text-sm">{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></div>; }
function toPrintPreview(document: PreviewDocument, index: number): InvoicePrintDocument { return { invoiceNo: `미발행-${index + 1}`, issueDate: document.issueDate, recipientName: document.siteName, recipientAddress: document.siteAddress, supplierBusinessRegistrationNo: document.supplier.businessRegistrationNo, supplierCompanyName: document.supplier.companyName, supplierRepresentativeName: document.supplier.representativeName, supplierAddress: document.supplier.address, supplierBusinessType: document.supplier.businessType, supplierBusinessItem: document.supplier.businessItem, supplierPhone: document.supplier.phone, supplyMessage: document.supplier.defaultMessage, subtotal: document.subtotal, memo: document.memo, templateConfig: document.templateConfig, lines: document.lines }; }
function localDateKey(value: Date) { const offset = value.getTimezoneOffset() * 60_000; return new Date(value.getTime() - offset).toISOString().slice(0, 10); }
