"use client";

import { Pencil, Plus, Search, Trash2, WandSparkles } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

import { useRealtimeRefresh } from "@/components/realtime-provider";
import { SmartInputDialog } from "@/components/smart-input/smart-input-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatSeoulDateTime } from "@/lib/date-time";
import type { SmartInputAppliedDraft } from "@/lib/smart-input/types";

type SiteOption = { id: string; code: string; name: string; isActive: boolean };
type ItemOption = { id: string; code: string; name: string; unit: string; standardSalesPrice: number; standardCostPrice: number; isActive: boolean };
type BillingMethod = "LEGACY_TOTAL" | "MONTHLY_RECURRING" | "PRORATED_TOTAL";
type PublicBillingMethod = Exclude<BillingMethod, "LEGACY_TOTAL">;
type ContractLineView = { id: string; billingMethod: BillingMethod; itemId: string; description: string | null; quantity: number; unit: string; standardSalesPriceSnapshot: number; appliedSalesPrice: number; standardCostPriceSnapshot: number; appliedCostPrice: number; priceOverrideReason: string | null; revenueStartDate: string; revenueEndDate: string; item: { id: string; code: string; name: string; isActive: boolean } };
export type ContractView = { id: string; contractNo: string; siteId: string; title: string; startDate: string; endDate: string; status: "DRAFT" | "ACTIVE" | "ENDED" | "CANCELED"; memo: string | null; version: number; updatedAt: string; site: SiteOption; lines: ContractLineView[] };
export type ContractList = { rows: ContractView[]; total: number; page: number; pageSize: number; totalPages: number };
type LineDraft = { id?: string; billingMethod: BillingMethod; legacyEligible: boolean; legacyPeriod?: { startDate: string; endDate: string }; itemId: string; description: string; quantity: number; appliedSalesPrice: number; appliedCostPrice: number; priceOverrideReason: string; revenueStartDate: string; revenueEndDate: string; standardSalesPrice: number; standardCostPrice: number };
type PayloadLine = Omit<LineDraft, "billingMethod" | "standardSalesPrice" | "standardCostPrice" | "legacyEligible" | "legacyPeriod"> & { billingMethod?: PublicBillingMethod };
type Payload = { contractNo: FormDataEntryValue | null; siteId: FormDataEntryValue | null; title: FormDataEntryValue | null; status: FormDataEntryValue | null; memo: FormDataEntryValue | null; lines: PayloadLine[] };
type Impact = { headerChanged: boolean; addedLines: number; modifiedLines: number; removedLines: number; affectedMonths: string[]; requiresConfirmation: boolean };

const statuses = ["DRAFT", "ACTIVE", "ENDED", "CANCELED"] as const;
const statusLabels = { DRAFT: "작성 중", ACTIVE: "진행", ENDED: "종료", CANCELED: "취소" };

export function ContractManager({ initialData, sites, items, canEdit }: { initialData: ContractList; sites: SiteOption[]; items: ItemOption[]; canEdit: boolean }) {
  const [data, setData] = useState(initialData); const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [siteId, setSiteId] = useState(""); const [loading, setLoading] = useState(false); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<ContractView | null>(null); const [smartOpen, setSmartOpen] = useState(false); const [smartDraft, setSmartDraft] = useState<SmartInputAppliedDraft | null>(null);
  async function load(page = 1) { setLoading(true); try { const params = new URLSearchParams({ q: query, status, siteId, page: String(page), pageSize: "20" }); const response = await fetch(`/api/contracts?${params}`); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "계약을 불러오지 못했습니다."); setData(body); } catch (error) { toast.error(error instanceof Error ? error.message : "계약을 불러오지 못했습니다."); } finally { setLoading(false); } }
  useRealtimeRefresh(["contract.changed"], () => void load(data.page));
  return <div className="space-y-4">
    <div className="flex flex-col gap-3 rounded-xl border bg-card p-4 xl:flex-row xl:items-end"><form className="flex flex-1 flex-col gap-3 sm:flex-row sm:items-end" onSubmit={(event) => { event.preventDefault(); void load(1); }}><div className="min-w-56 flex-1 space-y-1.5"><Label htmlFor="contract-search">검색</Label><Input id="contract-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="계약번호, 계약명, 현장, 품목" /></div><Select label="상태" value={status} onChange={setStatus} options={[{ value: "all", label: "전체" }, ...statuses.map((value) => ({ value, label: statusLabels[value] }))]} /><Select label="현장" value={siteId} onChange={setSiteId} options={[{ value: "", label: "전체 현장" }, ...sites.map((site) => ({ value: site.id, label: site.name }))]} /><Button type="submit" variant="outline" disabled={loading}><Search data-icon="inline-start" />조회</Button></form>{canEdit && <div className="flex gap-2"><Button variant="outline" disabled={!items.some((item) => item.isActive)} onClick={() => setSmartOpen(true)}><WandSparkles data-icon="inline-start" />스마트입력</Button><Button disabled={!items.some((item) => item.isActive)} onClick={() => { setEditing(null); setSmartDraft(null); setOpen(true); }}><Plus data-icon="inline-start" />계약 추가</Button></div>}</div>
    <div className="overflow-x-auto rounded-xl border bg-card"><Table><TableHeader><TableRow><TableHead>계약번호</TableHead><TableHead>계약명</TableHead><TableHead>현장</TableHead><TableHead>매출기간</TableHead><TableHead>품목</TableHead><TableHead className="min-w-56 text-right"><span className="block">품목 기준금액 합계</span><span className="block text-[11px] font-normal text-muted-foreground">월정액은 월별 금액, 일할·기존 계산은 배분 전 총액</span></TableHead><TableHead>상태</TableHead><TableHead>최종수정일</TableHead>{canEdit && <TableHead className="text-right">관리</TableHead>}</TableRow></TableHeader><TableBody>{data.rows.length === 0 ? <TableRow><TableCell colSpan={canEdit ? 9 : 8} className="h-28 text-center text-muted-foreground">조건에 맞는 계약이 없습니다.</TableCell></TableRow> : data.rows.map((row) => <TableRow key={row.id}><TableCell className="font-mono text-xs">{row.contractNo}</TableCell><TableCell className="font-medium">{row.title}</TableCell><TableCell>{row.site.name}</TableCell><TableCell className="whitespace-nowrap text-xs">{dateOnly(row.startDate)} ~ {dateOnly(row.endDate)}</TableCell><TableCell>{row.lines.length}개</TableCell><TableCell className="text-right tabular-nums">{row.lines.reduce((sum, line) => sum + Math.round(line.quantity * line.appliedSalesPrice), 0).toLocaleString()}</TableCell><TableCell><Badge variant={row.status === "ACTIVE" ? "secondary" : "outline"}>{statusLabels[row.status]}</Badge></TableCell><TableCell className="whitespace-nowrap text-xs tabular-nums">{formatSeoulDateTime(row.updatedAt)}</TableCell>{canEdit && <TableCell className="text-right"><Button size="sm" variant="ghost" onClick={() => { setEditing(row); setSmartDraft(null); setOpen(true); }}><Pencil data-icon="inline-start" />수정</Button></TableCell>}</TableRow>)}</TableBody></Table></div>
    <div className="flex items-center justify-between text-sm text-muted-foreground"><span>총 {data.total}건 · {data.page}/{data.totalPages} 페이지</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={data.page <= 1 || loading} onClick={() => void load(data.page - 1)}>이전</Button><Button size="sm" variant="outline" disabled={data.page >= data.totalPages || loading} onClick={() => void load(data.page + 1)}>다음</Button></div></div>
    {smartOpen && <SmartInputDialog target="CONTRACT" onClose={() => setSmartOpen(false)} onApply={(draft) => { setSmartDraft(draft); setEditing(null); setSmartOpen(false); setOpen(true); }} onRegistered={() => { setSmartOpen(false); void load(data.page); }} />}
    {open && <ContractEditor row={editing} draft={smartDraft} sites={sites} items={items} onOpenChange={setOpen} onSaved={() => void load(data.page)} />}
  </div>;
}

function ContractEditor({ row, draft, sites, items, onOpenChange, onSaved }: { row: ContractView | null; draft: SmartInputAppliedDraft | null; sites: SiteOption[]; items: ItemOption[]; onOpenChange: (open: boolean) => void; onSaved: () => void }) {
  const today = localDate(); const [lines, setLines] = useState<LineDraft[]>(() => row ? row.lines.map(lineFromView) : draft ? [lineFromSmartDraft(draft, items)] : [newLine(items.find((item) => item.isActive), today, today)]); const [busy, setBusy] = useState(false); const [impact, setImpact] = useState<Impact | null>(null); const [pending, setPending] = useState<Payload | null>(null);
  function clearPreview() { setImpact(null); setPending(null); }
  function changeLine(index: number, patch: Partial<LineDraft>) { setLines((current) => current.map((line, lineIndex) => lineIndex === index ? { ...line, ...patch } : line)); clearPreview(); }
  function changeBillingMethod(index: number, billingMethod: BillingMethod) { const line = lines[index]; if (!line) return; if (billingMethod === "MONTHLY_RECURRING") return changeLine(index, { billingMethod, revenueStartDate: monthOnly(line.revenueStartDate), revenueEndDate: monthOnly(line.revenueEndDate) }); if (billingMethod === "PRORATED_TOTAL" && line.billingMethod === "MONTHLY_RECURRING") return changeLine(index, { billingMethod, revenueStartDate: firstDayOfMonth(line.revenueStartDate), revenueEndDate: lastDayOfMonth(line.revenueEndDate) }); if (billingMethod === "LEGACY_TOTAL" && line.legacyPeriod) return changeLine(index, { billingMethod, revenueStartDate: line.legacyPeriod.startDate, revenueEndDate: line.legacyPeriod.endDate }); changeLine(index, { billingMethod }); }
  function changeItem(index: number, itemId: string) { const item = items.find((candidate) => candidate.id === itemId); if (!item) return; changeLine(index, { itemId, appliedSalesPrice: item.standardSalesPrice, appliedCostPrice: item.standardCostPrice, standardSalesPrice: item.standardSalesPrice, standardCostPrice: item.standardCostPrice, priceOverrideReason: "" }); }
  function payload(form: HTMLFormElement): Payload { const data = new FormData(form); return { contractNo: data.get("contractNo"), siteId: data.get("siteId"), title: data.get("title"), status: data.get("status"), memo: data.get("memo"), lines: lines.map((line) => ({ id: line.id, ...(line.billingMethod === "LEGACY_TOTAL" ? {} : { billingMethod: line.billingMethod }), itemId: line.itemId, description: line.description, quantity: line.quantity, appliedSalesPrice: line.appliedSalesPrice, appliedCostPrice: line.appliedCostPrice, priceOverrideReason: line.priceOverrideReason, revenueStartDate: line.revenueStartDate, revenueEndDate: line.revenueEndDate })) }; }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (lines.some((line) => line.billingMethod === "PRORATED_TOTAL" && spansMoreThanTwoCalendarMonths(line.revenueStartDate, line.revenueEndDate))) { toast.error("일할청구는 최대 두 달력 월에 걸쳐 등록할 수 있습니다."); return; } const body = payload(event.currentTarget); if (!row) return save(body); setBusy(true); try { const response = await fetch(`/api/contracts/${row.id}/change-preview`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "변경 영향을 확인하지 못했습니다."); setImpact(result.impact); setPending(body); } catch (error) { toast.error(error instanceof Error ? error.message : "변경 영향을 확인하지 못했습니다."); } finally { setBusy(false); } }
  async function save(body: Payload) { setBusy(true); try { const response = await fetch(`/api/contracts${row ? `/${row.id}` : ""}`, { method: row ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(row ? { ...body, version: row.version } : body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "계약을 저장하지 못했습니다."); toast.success("계약을 저장했습니다."); onOpenChange(false); onSaved(); } catch (error) { toast.error(error instanceof Error ? error.message : "계약을 저장하지 못했습니다."); } finally { setBusy(false); } }
  return <Dialog open onOpenChange={onOpenChange}><DialogContent className="max-h-[94svh] overflow-y-auto sm:max-w-6xl"><DialogHeader><DialogTitle>계약 {row ? "수정" : "추가"}</DialogTitle><DialogDescription>계약 전체 매출기간은 품목별 매출기간에서 자동 산정됩니다. 다른 단가를 적용할 때는 예외 사유를 입력하세요.</DialogDescription></DialogHeader><form key={row?.id ?? "new"} className="space-y-5" onSubmit={submit} onChange={clearPreview}>
    <div className="grid gap-4 md:grid-cols-3"><Field label="계약번호" name="contractNo" defaultValue={row?.contractNo ?? ""} placeholder="비우면 자동 생성" /><div className="space-y-1.5"><Label htmlFor="siteId">현장</Label><select id="siteId" name="siteId" defaultValue={row?.siteId ?? draft?.siteId ?? sites.find((site) => site.isActive)?.id} className="h-9 w-full rounded-lg border bg-background px-3 text-sm" required>{sites.map((site) => <option key={site.id} value={site.id} disabled={!site.isActive && row?.siteId !== site.id}>{site.name}{site.isActive ? "" : " (중지)"}</option>)}</select></div><Field label="계약명" name="title" defaultValue={row?.title ?? draft?.title ?? ""} required /><div className="space-y-1.5"><Label htmlFor="status">상태</Label><select id="status" name="status" defaultValue={row?.status ?? "ACTIVE"} className="h-9 w-full rounded-lg border bg-background px-3 text-sm">{statuses.map((value) => <option key={value} value={value}>{statusLabels[value]}</option>)}</select></div><Field className="md:col-span-2" label="메모" name="memo" defaultValue={row?.memo ?? (draft ? "문장으로 빠른 입력에서 적용" : "")} /></div>
    <div className="space-y-3"><div className="flex items-center justify-between"><div><h3 className="font-semibold">계약 품목</h3><p className="text-xs text-muted-foreground">품목별로 월정액 또는 최대 두 달의 일할청구를 선택합니다.</p></div><Button type="button" size="sm" variant="outline" disabled={!items.some((item) => item.isActive)} onClick={() => { const item = items.find((candidate) => candidate.isActive); if (item) setLines((current) => { const previous = current.at(-1); return [...current, newLine(item, previous?.revenueStartDate ?? today, previous?.revenueEndDate ?? today)]; }); clearPreview(); }}><Plus data-icon="inline-start" />행 추가</Button></div>
      {lines.map((line, index) => {
        const item = items.find((candidate) => candidate.id === line.itemId);
        const overridden = line.appliedSalesPrice !== line.standardSalesPrice || line.appliedCostPrice !== line.standardCostPrice;
        const invalidProratedPeriod = line.billingMethod === "PRORATED_TOTAL" && spansMoreThanTwoCalendarMonths(line.revenueStartDate, line.revenueEndDate);
        return <div key={line.id ?? index} className={`grid gap-3 rounded-xl border p-3 lg:grid-cols-12 ${overridden ? "border-amber-300 bg-amber-50/50" : "bg-muted/60"}`}>
          <div className="space-y-1 lg:col-span-3"><Label>품목</Label><select value={line.itemId} onChange={(event) => changeItem(index, event.target.value)} className="h-9 w-full rounded-lg border bg-card px-2 text-sm">{items.map((option) => <option key={option.id} value={option.id} disabled={!option.isActive && option.id !== line.itemId}>{option.name} ({option.code})</option>)}</select><p className="text-xs text-muted-foreground">단위 {item?.unit}</p></div>
          <div className="space-y-1 lg:col-span-2"><Label>청구 방식</Label><select value={line.billingMethod} onChange={(event) => changeBillingMethod(index, event.target.value as BillingMethod)} className="h-9 w-full rounded-lg border bg-card px-2 text-sm"><option value="MONTHLY_RECURRING">월정액</option><option value="PRORATED_TOTAL">일할청구</option>{line.legacyEligible && <option value="LEGACY_TOTAL">기존 계산 유지</option>}</select></div>
          <LineNumber label="수량" value={line.quantity} onChange={(value) => changeLine(index, { quantity: value })} />
          <LineNumber label={`매출단가 (표준 ${line.standardSalesPrice.toLocaleString()})`} value={line.appliedSalesPrice} onChange={(value) => changeLine(index, { appliedSalesPrice: value })} span="lg:col-span-2" />
          <LineNumber label={`매입단가 (표준 ${line.standardCostPrice.toLocaleString()})`} value={line.appliedCostPrice} onChange={(value) => changeLine(index, { appliedCostPrice: value })} span="lg:col-span-2" />
          <div className="space-y-1 lg:col-span-2"><Label>{line.billingMethod === "MONTHLY_RECURRING" ? "시작월" : "매출 시작"}</Label><Input type={line.billingMethod === "MONTHLY_RECURRING" ? "month" : "date"} value={line.revenueStartDate} aria-invalid={invalidProratedPeriod} onChange={(event) => changeLine(index, { revenueStartDate: event.target.value })} /></div>
          <div className="space-y-1 lg:col-span-2"><Label>{line.billingMethod === "MONTHLY_RECURRING" ? "종료월" : "매출 종료"}</Label><Input type={line.billingMethod === "MONTHLY_RECURRING" ? "month" : "date"} value={line.revenueEndDate} aria-invalid={invalidProratedPeriod} onChange={(event) => changeLine(index, { revenueEndDate: event.target.value })} /></div>
          {invalidProratedPeriod && <p className="text-xs text-destructive lg:col-span-12">일할청구는 최대 두 달력 월에 걸쳐 등록할 수 있습니다.</p>}
          <div className="space-y-1 lg:col-span-5"><Label>설명</Label><Input value={line.description} onChange={(event) => changeLine(index, { description: event.target.value })} /></div>
          <div className="space-y-1 lg:col-span-6"><Label>단가 예외 사유 {overridden && <span className="text-amber-700">(필수)</span>}</Label><Input value={line.priceOverrideReason} onChange={(event) => changeLine(index, { priceOverrideReason: event.target.value })} placeholder={overridden ? "A/S, 현장 협의 등 사유" : "표준단가 사용"} /></div>
          <div className="flex items-end justify-end lg:col-span-1"><Button type="button" size="icon-sm" variant="ghost" disabled={lines.length === 1} onClick={() => { setLines((current) => current.filter((_, lineIndex) => lineIndex !== index)); clearPreview(); }}><Trash2 /><span className="sr-only">행 삭제</span></Button></div>
        </div>;
      })}
    </div>
    {impact && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><p className="font-semibold text-amber-900">변경 영향 확인</p><p className="mt-1">헤더 변경 {impact.headerChanged ? "있음" : "없음"} · 추가 {impact.addedLines}행 · 수정 {impact.modifiedLines}행 · 제외 {impact.removedLines}행</p><p className="mt-1 text-amber-800">영향 월: {impact.affectedMonths.join(", ") || "없음"}</p><p className="mt-2 text-xs text-muted-foreground">이 월들의 미확정 자동 매출 재계산 대상을 함께 표시합니다.</p></div>}
    <div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>취소</Button>{impact && pending ? <Button type="button" disabled={busy} onClick={() => void save(pending)}>변경 확인 후 저장</Button> : <Button type="submit" disabled={busy}>{busy ? "확인 중..." : row ? "변경 영향 확인" : "진행 계약으로 저장"}</Button>}</div>
  </form></DialogContent></Dialog>;
}

function newLine(item: ItemOption | undefined, start: string, end: string): LineDraft { return { billingMethod: "MONTHLY_RECURRING", legacyEligible: false, itemId: item?.id ?? "", description: "", quantity: 1, appliedSalesPrice: item?.standardSalesPrice ?? 0, appliedCostPrice: item?.standardCostPrice ?? 0, priceOverrideReason: "", revenueStartDate: monthOnly(start), revenueEndDate: monthOnly(end), standardSalesPrice: item?.standardSalesPrice ?? 0, standardCostPrice: item?.standardCostPrice ?? 0 }; }
function lineFromView(line: ContractLineView): LineDraft { const startDate = dateOnly(line.revenueStartDate); const endDate = dateOnly(line.revenueEndDate); const legacyEligible = line.billingMethod === "LEGACY_TOTAL"; return { id: line.id, billingMethod: line.billingMethod, legacyEligible, legacyPeriod: legacyEligible ? { startDate, endDate } : undefined, itemId: line.itemId, description: line.description ?? "", quantity: line.quantity, appliedSalesPrice: line.appliedSalesPrice, appliedCostPrice: line.appliedCostPrice, priceOverrideReason: line.priceOverrideReason ?? "", revenueStartDate: line.billingMethod === "MONTHLY_RECURRING" ? monthOnly(startDate) : startDate, revenueEndDate: line.billingMethod === "MONTHLY_RECURRING" ? monthOnly(endDate) : endDate, standardSalesPrice: line.standardSalesPriceSnapshot, standardCostPrice: line.standardCostPriceSnapshot }; }
function lineFromSmartDraft(draft: SmartInputAppliedDraft, items: ItemOption[]): LineDraft { const item = items.find((candidate) => candidate.id === draft.itemId); return { billingMethod: "MONTHLY_RECURRING", legacyEligible: false, itemId: item?.id ?? "", description: draft.description, quantity: draft.quantity ?? 1, appliedSalesPrice: draft.appliedSalesPrice ?? item?.standardSalesPrice ?? 0, appliedCostPrice: draft.appliedCostPrice ?? item?.standardCostPrice ?? 0, priceOverrideReason: draft.priceOverrideReason, revenueStartDate: monthOnly(draft.startDate), revenueEndDate: monthOnly(draft.endDate), standardSalesPrice: item?.standardSalesPrice ?? 0, standardCostPrice: item?.standardCostPrice ?? 0 }; }
function LineNumber({ label, value, onChange, span = "lg:col-span-1" }: { label: string; value: number; onChange: (value: number) => void; span?: string }) { return <div className={`space-y-1 ${span}`}><Label>{label}</Label><Input type="number" min="0" step="any" value={value} onChange={(event) => onChange(Number(event.target.value))} /></div>; }
function Field({ label, className = "", ...props }: React.ComponentProps<typeof Input> & { label: string; className?: string }) { const id = String(props.name); return <div className={`space-y-1.5 ${className}`}><Label htmlFor={id}>{label}</Label><Input id={id} {...props} /></div>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: Array<{ value: string; label: string }> }) { return <div className="space-y-1.5"><Label>{label}</Label><select value={value} onChange={(event) => onChange(event.target.value)} className="h-9 min-w-32 rounded-lg border bg-background px-3 text-sm">{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></div>; }
function dateOnly(value?: string | null) { return value?.slice(0, 10) ?? ""; }
function monthOnly(value: string) { return value.slice(0, 7); }
function firstDayOfMonth(value: string) { return `${monthOnly(value)}-01`; }
function lastDayOfMonth(value: string) { const [year, month] = monthOnly(value).split("-").map(Number); return new Date(Date.UTC(year, month, 0)).toISOString().slice(0, 10); }
function spansMoreThanTwoCalendarMonths(start: string, end: string) { if (!start || !end) return false; const [startYear, startMonth] = monthOnly(start).split("-").map(Number); const [endYear, endMonth] = monthOnly(end).split("-").map(Number); return (endYear - startYear) * 12 + endMonth - startMonth > 1; }
function localDate() { const now = new Date(); return [now.getFullYear(), String(now.getMonth() + 1).padStart(2, "0"), String(now.getDate()).padStart(2, "0")].join("-"); }
